import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Navbar from "../../components/Navbar";
import "@/app/globals.css";
import { PostProvider } from "@/utils/PostProvider";
import { AuthProvider } from "@/utils/AuthContext";
import { getUser } from "@/utils/getUser";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user = await getUser();
  return (
    <AuthProvider
    user={user ? {
      fullName: user.name,
      email: user.email,
      username: user.username,
    } : null}
  >
    <PostProvider posts={[]}>
      <Navbar />
      <main className="ml-[73px] xl:ml-[245px]">{children}</main>
    </PostProvider>
    </AuthProvider>
  );
}
