import type { Metadata } from "next";
import Navbar from "../../components/Navbar";
import "@/app/globals.css";
import AppProvider from "@/utils/AppProvider";
import { getUser } from "@/utils/getData";
import Error from "@/components/Error";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user = await getUser();
  return (
    <AppProvider user={user}>
      <Navbar />
      <main className="ml-[73px] xl:ml-[245px]">
        <Error>{children}</Error>
      </main>
    </AppProvider>
  );
}
